// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project.Models;

public partial class Car
{
    public int CarId { get; set; }

    public int CarMark { get; set; }

    public int CarModel { get; set; }

    public int CarCountry { get; set; }

    public int CarType { get; set; }

    public string CarVin { get; set; }

    public string CarPts { get; set; }

    public DateOnly CarDate { get; set; }

    public int CarColor { get; set; }

    public string CarPhoto { get; set; }

    public float CarPrice { get; set; }

    public bool CarBlock { get; set; }

    public sbyte CarDelete { get; set; }

    public virtual CarsColor CarColorNavigation { get; set; }

    public virtual CarsCountry CarCountryNavigation { get; set; }

    public virtual CarsMark CarMarkNavigation { get; set; }

    public virtual CarsModel CarModelNavigation { get; set; }

    public virtual CarsType CarTypeNavigation { get; set; }

    public virtual ICollection<MmOrdersCar> MmOrdersCars { get; set; } = new List<MmOrdersCar>();
}