// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project.Models;

public partial class Car
{
    public int CarId { get; set; }

    /// <summary>
    /// Производитель(марка)
    /// </summary>
    public int CarMark { get; set; }

    /// <summary>
    /// Модель
    /// </summary>
    public int CarModel { get; set; }

    /// <summary>
    /// Страна производства
    /// </summary>
    public int CarCountry { get; set; }

    /// <summary>
    /// Тип
    /// </summary>
    public int CarType { get; set; }

    /// <summary>
    /// VIN-код
    /// </summary>
    public string CarVin { get; set; }

    /// <summary>
    /// ПТС авто
    /// </summary>
    public string CarPts { get; set; }

    /// <summary>
    /// Дата производства
    /// </summary>
    public DateOnly? CarDate { get; set; }

    /// <summary>
    /// Цвет
    /// </summary>
    public int CarColor { get; set; }

    /// <summary>
    /// Фотография
    /// </summary>
    public byte[] CarPhoto { get; set; }

    /// <summary>
    /// Цена
    /// </summary>
    public int CarPrice { get; set; }

    /// <summary>
    /// Номер заказа
    /// </summary>
    public int CarBlock { get; set; }

    /// <summary>
    /// Метка удаления
    /// </summary>
    public bool Delete { get; set; }

    public virtual CarsColor CarColorNavigation { get; set; }

    public virtual CarsCountry CarCountryNavigation { get; set; }

    public virtual CarsMark CarMarkNavigation { get; set; }

    public virtual CarsModel CarModelNavigation { get; set; }

    public virtual CarsType CarTypeNavigation { get; set; }

    public virtual ICollection<MmOrdersCar> MmOrdersCars { get; set; } = new List<MmOrdersCar>();
}