// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project.Models;

public partial class CarsModel
{
    public int ModelId { get; set; }

    public string ModelName { get; set; }

    public bool ModelDelete { get; set; }

    public virtual ICollection<Car> Cars { get; set; } = new List<Car>();

    public virtual ICollection<MmMarkModel> MmMarkModels { get; set; } = new List<MmMarkModel>();

    public virtual ICollection<MmModelCountry> MmModelCountries { get; set; } = new List<MmModelCountry>();
}