// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project.Models;

public partial class CarsCountry
{
    public int CountryId { get; set; }

    /// <summary>
    /// Наименование
    /// </summary>
    public string CountryName { get; set; }

    /// <summary>
    /// Метка удаления
    /// </summary>
    public bool Delete { get; set; }

    public virtual ICollection<Car> Cars { get; set; } = new List<Car>();

    public virtual ICollection<MmModelCountry> MmModelCountries { get; set; } = new List<MmModelCountry>();
    
    // Поле сортировки по умолчанию
    public static string DefaultSortProperty => nameof(CountryName);
}