// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project.Models;

public partial class CarsColor
{
    public int ColorId { get; set; }

    public string ColorName { get; set; }

    public bool ColorDelete { get; set; }

    public virtual ICollection<Car> Cars { get; set; } = new List<Car>();
}