// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project.Models;

public partial class MmDepartmentFunction
{
    public int Id { get; set; }

    public int DepartmentId { get; set; }

    public int FunctionId { get; set; }

    public virtual UsersDepartment Department { get; set; }

    public virtual UsersFunction Function { get; set; }
}