// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project.Models;

public partial class MmMarkModel
{
    public int Id { get; set; }

    public int MarkId { get; set; }

    public int ModelId { get; set; }

    public virtual CarsMark Mark { get; set; }

    public virtual CarsModel Model { get; set; }
}