// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project.Models;

public partial class MmOrdersStatus
{
    public int Id { get; set; }

    /// <summary>
    /// id заказа
    /// </summary>
    public int OrderId { get; set; }

    /// <summary>
    /// id статуса
    /// </summary>
    public int StatusId { get; set; }

    /// <summary>
    /// Дата смены статуса
    /// </summary>
    public DateTime Date { get; set; }

    public virtual Order Order { get; set; }

    public virtual OrdersStatus Status { get; set; }
}