// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project.Models;

public partial class MmOrdersStatus
{
    public int Id { get; set; }

    public int OrderId { get; set; }

    public int StatusId { get; set; }

    public DateTime Date { get; set; }

    public virtual Order Order { get; set; }

    public virtual OrdersStatus Status { get; set; }
}