// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project.Models;

public partial class OrdersPayment
{
    public int PaymentId { get; set; }

    /// <summary>
    /// Наименование
    /// </summary>
    public string PaymentName { get; set; }

    /// <summary>
    /// Метка удаления
    /// </summary>
    public bool Delete { get; set; }

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}