// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project.Models;

public partial class OrdersDelivery
{
    public int DeliveryId { get; set; }

    public string DeliveryName { get; set; }

    public bool DeliveryDelete { get; set; }

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}