// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project.Models;

public partial class Order
{
    public int OrdersId { get; set; }

    public int OrdersClient { get; set; }

    public int? OrdersUser { get; set; }

    public DateTime OrdersData { get; set; }

    public int OrdersPayment { get; set; }

    public int OrdersDelivery { get; set; }

    public string OrdersAddress { get; set; }

    public bool OrdersDelete { get; set; }

    public virtual ICollection<MmOrdersCar> MmOrdersCars { get; set; } = new List<MmOrdersCar>();

    public virtual ICollection<MmOrdersStatus> MmOrdersStatuses { get; set; } = new List<MmOrdersStatus>();

    public virtual OrdersClient OrdersClientNavigation { get; set; }

    public virtual OrdersDelivery OrdersDeliveryNavigation { get; set; }

    public virtual OrdersPayment OrdersPaymentNavigation { get; set; }

    public virtual User OrdersUserNavigation { get; set; }
}