// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project.Models;

public partial class OrdersClient
{
    public int ClientId { get; set; }

    public string ClientLogin { get; set; }

    public string ClientPassword { get; set; }

    public string ClientMail { get; set; }

    public string ClientName { get; set; }

    public string ClientSurname { get; set; }

    public string ClientPhone { get; set; }

    public DateOnly? ClientBirthday { get; set; }

    public DateTime ClientDateRegistration { get; set; }

    public bool ClientFlagDelete { get; set; }

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}