// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project.Models;

public partial class Order
{
    public int OrdersId { get; set; }

    /// <summary>
    /// id клиента
    /// </summary>
    public int OrdersClient { get; set; }

    /// <summary>
    /// id сотрудника
    /// </summary>
    public int? OrdersUser { get; set; }

    /// <summary>
    /// Дата создания заказа
    /// </summary>
    public DateTime? OrdersData { get; set; }

    /// <summary>
    /// Тип оплаты
    /// </summary>
    public int OrdersPayment { get; set; }

    /// <summary>
    /// Тип доставки
    /// </summary>
    public int OrdersDelivery { get; set; }

    /// <summary>
    /// Адрес доставки
    /// </summary>
    public string OrdersAddress { get; set; }

    /// <summary>
    /// Метка удаления
    /// </summary>
    public bool Delete { get; set; }

    public virtual ICollection<MmOrdersCar> MmOrdersCars { get; set; } = new List<MmOrdersCar>();

    public virtual ICollection<MmOrdersStatus> MmOrdersStatuses { get; set; } = new List<MmOrdersStatus>();

    public virtual OrdersClient OrdersClientNavigation { get; set; }

    public virtual OrdersDelivery OrdersDeliveryNavigation { get; set; }

    public virtual OrdersPayment OrdersPaymentNavigation { get; set; }

    public virtual User OrdersUserNavigation { get; set; }
}