// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project.Models;

public partial class SitePage
{
    public int PageId { get; set; }

    public int PageNumber { get; set; }

    public string PageNameEng { get; set; }

    public string PageNameRus { get; set; }

    public string PageIcon { get; set; }

    public sbyte Delete { get; set; }
}