// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project.Models;

public partial class UsersDepartment
{
    public int DepartmentId { get; set; }

    /// <summary>
    /// Наименование
    /// </summary>
    public string DepartmentName { get; set; }

    /// <summary>
    /// Описание
    /// </summary>
    public string DepartmentDescription { get; set; }

    /// <summary>
    /// E-mail отдела
    /// </summary>
    public string DepartmentMail { get; set; }

    /// <summary>
    /// Метка удаления
    /// </summary>
    public bool Delete { get; set; }

    public virtual ICollection<User> Users { get; set; } = new List<User>();
}