// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project.Models;

public partial class UsersDepartmment
{
    public int DepartmentId { get; set; }

    public string DepartmentName { get; set; }

    public string DepartmentDescription { get; set; }

    public string DepartmentMail { get; set; }

    public bool DepartmentFlagDelete { get; set; }

    public virtual ICollection<User> Users { get; set; } = new List<User>();
}