// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project.Models;

public partial class UsersFunction
{
    public int FunctionId { get; set; }

    /// <summary>
    /// Наименование
    /// </summary>
    public string FunctionName { get; set; }

    /// <summary>
    /// Описание
    /// </summary>
    public string FunctionDescription { get; set; }

    /// <summary>
    /// Метка удаления
    /// </summary>
    public bool Delete { get; set; }

    public virtual ICollection<User> Users { get; set; } = new List<User>();
}