// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project.Models;

public partial class UsersFunction
{
    public int FunctionId { get; set; }

    public string FunctionName { get; set; }

    public string FunctionDescription { get; set; }

    public bool FunctionDelete { get; set; }

    public virtual ICollection<User> Users { get; set; } = new List<User>();
}