// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project.Models;

public partial class User
{
    public int UsersId { get; set; }

    public string UsersLogin { get; set; }

    public string UsersPassword { get; set; }

    public string UsersMail { get; set; }

    public int UsersDepartment { get; set; }

    public int UsersFunction { get; set; }

    public int UsersStatus { get; set; }

    public DateOnly? UsersStatusChange { get; set; }

    public string UsersName { get; set; }

    public string UsersSurname { get; set; }

    public string UsersPatronymic { get; set; }

    public string UsersPhone { get; set; }

    public DateOnly? UsersBirthday { get; set; }

    public DateOnly UsersStartWork { get; set; }

    public string UsersPermissions { get; set; }

    public bool UsersFlagDelete { get; set; }

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual UsersDepartment UsersDepartmentNavigation { get; set; }

    public virtual UsersFunction UsersFunctionNavigation { get; set; }

    public virtual UsersStatus UsersStatusNavigation { get; set; }
}